# Type Path Mode User Group Age Argument
d /run/systemd-inferenced 0755 inferenced inferenced -
d /var/log/systemd-inferenced 0750 inferenced inferenced -
d /var/lib/systemd-inferenced 0750 inferenced inferenced -
d /etc/systemd/inferenced.conf.d 0755 root root -
